name: nothingtodo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #table_calendar: ^3.0.9
  #flutter_calendar_carousel: ^2.4.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  #firebase_messaging: ^14.7.16
  image_cropper: ^5.0.1
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  device_calendar: ^4.3.2
  flutter_colorpicker: ^1.0.3
  fl_chart: ^0.66.0
  intl: ^0.18.0
  sqflite: ^2.3.2
  path: ^1.8.3
  flukit: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
